---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2020-10-12 - 15:28:41 +0000
  labels:
    app.kubernetes.io/name: garena-game
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: garena-game
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2020-10-12 - 15:28:41 +0000
  labels:
    app.kubernetes.io/name: garena-game
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: garena-game
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: garena-game
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2020-10-12 - 15:28:41 +0000
  labels:
    app.kubernetes.io/name: garena-game
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: garena-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: garena-game
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2020-10-12 - 15:28:41 +0000
      labels:
        app.kubernetes.io/name: garena-game
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ecrafteventagency/garena_game:1.0
          imagePullPolicy: Always
          name: garena-game
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
      serviceAccount: garena-game